### PR TITLE
Update to use .NET 4.6 and StackExchange.Redis 1.2.0

### PR DESCRIPTION
**Pull request by mscrivo**
Hey @collinsauve  would you mind testing this build and pushing it to your nuget repo?  I have no idea how it works.   Maybe document the build and publish steps?

### CODE REVIEW

**Comment by collinsauve** [comment]
@mscrivo what's your timeline for switching to new Redis library?  How soon do you need this?

**Comment by mscrivo** [comment]
No rush, whenever you have some time.  I don't have a timeline for this one, it's more of a maintenance thing.

**Comment by mscrivo** [comment]
It might be good to actually bring it over to the Nudge org, and set up a TC build for it that auto-publishes it when there are changes.

**Comment by collinsauve** [comment]
@mguissine @awr do we have any other repos that auto-publish to nuget that I can use as an example? ie Nudge.Tooling?

**Comment by awr** [comment]
if you leave it in your own repo, you can take advantage of appveyor CI like I'm doing with https://github.com/awr/KafkaClient. It can do publishing to nuget if you want

if you want to move over to the nudge org, take a look at the config of `3.0 Manual Deploy of Nudge.Tooling` in TC

**Comment by mscrivo** [comment]
if you leave it in your own repo it's not very conducive to team work though.  How does someone, who's not you, update the KafkaClient?    Bigger discussion maybe, but the less ways we have of doing things, the better, and the more transparent they are, the better.

**Comment by collinsauve** [comment]
Agreed, I'd like to pull this to be owned by the Nudge org rather than just myself.

Can we still use appveyor for that?

**Comment by awr** [comment]
It's only available for OSS afaik, so it gets muddy when it's in the company account. Additionally, you'd need to give access to the Nudge org github account (which I'm not sure is a good idea), which is a security liability.

@mscrivo it's just like any other OSS project -- create a pull request.

**Comment by mscrivo** [comment]
@awr not really, OSS projects are usually under and org and multiple people have the ability to merge PR's ... what if you're out sick or on vacation? :)

**Comment by awr** [comment]
Not sure how that's different from an OSS project, to be honest.

In this case, changes are very slow moving -- so the concern about being a few days off seems a bit extreme.

If we do have projects that are being contributed to regularly, those individuals can simply be added as contributors ...

**Comment by collinsauve** [comment]
Moving the repo shouldn't change whether it's OSS, but I see your point
about the oauth permissions.  What permissions do they ask for?

**Comment by awr** [comment]
If I remember correctly, it asks for permissions to the org, and isn't
clear that it's restricted to a particular repo -- potentially giving full
access to our source.

**Comment by collinsauve** [comment]
Okay I got appveyor all working - changes assembly versions, builds release, runs tests, and produces a nupkg.

Unfortunately that caused major merge conflicts here.  I had to perform these changes:
* applied some of the same meta-data changes you did (ie change author, projectUrl),
* removed the old ps1 files he was using to build
* reorganized the project structure
* fixed tests so they actually ran `redis-server.exe` (it looks like previous author's tests never actually ran on appveyor)

@mscrivo Can we go over your intended changes to support .net v4.6?

**Comment by collinsauve** [comment]
I've published and unlisted new version to nuget here: https://www.nuget.org/packages/redlock-cs-async/2.0.21

**Comment by mscrivo** [comment]
thank you!

**Pull request closed without merging**
